# Generated by Django 3.2.6 on 2021-08-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('event_pk', 'username')},
        ),
    ]
