# Generated by Django 3.2.6 on 2021-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210802_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='item_max',
            field=models.PositiveSmallIntegerField(help_text='Soft max for slugs to crawl towards'),
        ),
    ]
