# Generated by Django 3.2.6 on 2021-08-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_item_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='player',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='event',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
