# Generated by Django 3.2.6 on 2021-08-04 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
